window.GIFT_AXHUB_SOURCE={documentVersion:1,format:"axhub-annotation-source",data:{version:2,prototypeName:"laka-gift-system-admin-wireframe",pageId:"tabs",updatedAt:1784505600000,nodes:[
{id:"prototype-root",index:1,title:"原型状态控制",locator:{selectors:['[data-annotation-id="prototype-root"]'],fingerprint:"app|prototype-root",path:[]},annotationText:"通过 State 切换后台页面与评审状态。线框图只验证信息架构、操作流程和业务逻辑，不代表正式视觉设计。",color:"#555555",images:[],controls:[{type:"segmented",attributeId:"admin_page",displayName:"后台页面",initialValue:"tabs",options:[{label:"Tab 配置",value:"tabs"},{label:"面板配置",value:"placement"},{label:"玩法配置",value:"play"},{label:"Banner 配置",value:"banner"},{label:"全服公告",value:"announcement"}]},{type:"segmented",attributeId:"review_state",displayName:"评审状态",initialValue:"list",options:[{label:"列表",value:"list"},{label:"新增/修改",value:"edit"}]}],createdAt:1784505600000,updatedAt:1784505600000},
{id:"gift-navigation",index:2,title:"礼物管理新结构",locator:{selectors:['[data-annotation-id="gift-navigation"]'],fingerprint:"nav|gift-navigation",path:[]},annotationText:"保留已有礼物资源配置，新增 Tab、玩法和 Banner 配置；礼物面板配置只负责投放。",color:"#555555",images:[],createdAt:1784505600000,updatedAt:1784505600000},
{id:"tab-config-page",index:3,title:"礼物 Tab 配置",pageId:"tabs",locator:{selectors:['[data-annotation-id="tab-config-page"]'],fingerprint:"section|tabs",path:[]},annotationText:"独立管理 Tab 名称、场景、大区、有效期、默认项和排序，替代原来的自由文本分组名称。",color:"#222222",images:[],createdAt:1784505600000,updatedAt:1784505600000},
{id:"placement-page",index:4,title:"礼物面板配置",pageId:"placement",locator:{selectors:['[data-annotation-id="placement-page"]'],fingerprint:"section|placement",path:[]},annotationText:"负责把已有礼物投放到场景和 Tab；删除人工角标字段，玩法与赠送门槛只读展示。",color:"#222222",images:[],createdAt:1784505600000,updatedAt:1784505600000},
{id:"play-config-page",index:5,title:"礼物玩法配置",pageId:"play",locator:{selectors:['[data-annotation-id="play-config-page"]'],fingerprint:"section|play",path:[]},annotationText:"玩法决定送礼后的真实能力。角标由主玩法自动生成；财富/VIP 属于门槛，New/Limited 属于运营标签。",color:"#222222",images:[],createdAt:1784505600000,updatedAt:1784505600000},
{id:"play-flow",index:6,title:"玩法配置流程",pageId:"play",locator:{selectors:['[data-annotation-id="play-flow"]'],fingerprint:"flow|play",path:[]},annotationText:"先选礼物与主玩法，再填写参数和赠送门槛，最终由系统生成前端展示标识并执行发布校验。",color:"#777777",images:[],createdAt:1784505600000,updatedAt:1784505600000},
{id:"banner-config-page",index:7,title:"礼物说明 Banner 配置",pageId:"banner",locator:{selectors:['[data-annotation-id="banner-config-page"]'],fingerprint:"section|banner",path:[]},annotationText:"说明 Banner 是礼物面板中的详情入口，不由送礼触发，也不承担全服公告。模板 Banner 修改文本即可生效；定制 Banner 每次需求独立上传完整样式。",color:"#222222",images:[],createdAt:1784505600000,updatedAt:1784505600000},
{id:"announcement-config-page",index:8,title:"平台级全服公告配置",pageId:"announcement",locator:{selectors:['[data-annotation-id="announcement-config-page"]'],fingerprint:"section|announcement",path:[]},annotationText:"全服公告按触发来源、触发事件、触发对象和附加触发条件逐级联动。客户端预置公告样式，后台不建设独立模板页面，只配置文案、范围、跳转、队列、频控、隐私和风控。",color:"#222222",images:[],createdAt:1784592000000,updatedAt:1784678400000}
]},markdownMap:{},assetMap:{},directory:{nodes:[{type:"folder",id:"gift-admin",title:"礼物系统后台",defaultExpanded:true,children:[{type:"route",id:"route-tabs",title:"1. 礼物 Tab 配置",route:"tabs"},{type:"route",id:"route-placement",title:"2. 礼物面板配置",route:"placement"},{type:"route",id:"route-play",title:"3. 礼物玩法配置",route:"play"},{type:"route",id:"route-banner",title:"4. 礼物说明 Banner",route:"banner"},{type:"route",id:"route-announcement",title:"5. 全服公告配置",route:"announcement"},{type:"markdown",id:"model-note",title:"配置关系说明",markdown:"# 配置关系\n\n- 礼物资源：已有事实源\n- Tab：决定礼物放在哪里\n- 面板投放：决定场景、区域、时间和排序\n- 玩法：决定礼物业务结果并声明是否调用公告\n- 说明 Banner：展示玩法入口，点击查看礼物详情\n- 全服公告：平台广播能力，统一承接多个业务事件"},{type:"markdown",id:"open-questions",title:"待确认问题",markdown:"# 待确认\n\n1. 全服公告最终覆盖运营大区、国家还是全站？\n2. 关系和等级公告是否默认关闭？\n3. 单用户公告频控和队列上限？\n4. 模板 Banner 文案字数和素材格式？\n5. 音乐礼物如何与房间背景音乐混音？"}]}]}};
